server:
  port: ${PORT:8080}

spring:
  application:
    name: java-interview-backend
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/java_interview
#    username: postgres
#    password: 123456
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.interview.entity
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto

# Knife4j配置
knife4j:
  enable: true
  setting:
    language: zh_cn